apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-applgeneral
data:
  app.auth-server.url:
  app.db.server:
  app.db.name:
  rabbitmq.user:
  rabbitmq.psw:
  rabbitmq.server:
  rabbitmq.port:

---
apiVersion: v1
kind: Secret
metadata:
  name: scrt-db
data:
  user:
  password:

---
apiVersion: v1
kind: Secret
metadata:
  name: scrt-auth
data:
  user:
  password:

---
apiVersion: v1
kind: Secret
metadata:
  name: scrt-applstorage
data:
  azurestorageaccountname:
  azurestorageaccountkey: