kind: Service
apiVersion: v1
metadata:
  name: report-service
  labels:
    deployment: report-service
spec:
  selector:
    app: report-service-app
  ports:
    - name: report-service-port
      protocol: TCP
      port: 8815
      targetPort: 8815

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  labels:
    deployment: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service-app
  template:
    metadata:
      labels:
        app: report-service-app
    spec:
      containers:
        - name: report-service-container
          image: myregistry.azurecr.io/app/report-service:latest
          env:
            - name: auth-server.url
              valueFrom:
                configMapKeyRef:
                  name: cfg-applgeneral
                  key: app.auth-server.url
            - name: auth-server.user
              valueFrom:
                secretKeyRef:
                  name: scrt-auth
                  key: user
            - name: auth-server.secret
              valueFrom:
                secretKeyRef:
                  name: scrt-auth
                  key: password 
            - name: app.eureka.server
              valueFrom:
                configMapKeyRef:
                  name: cfg-applgeneral
                  key: app.eureka.server
            - name: app.db.server
              valueFrom:
                configMapKeyRef:
                  name: cfg-applgeneral
                  key: app.db.server
            - name: app.db.name
              valueFrom:
                configMapKeyRef:
                  name: cfg-applgeneral
                  key: app.db.name
            - name: app.db.user
              valueFrom:
                secretKeyRef:
                  name: scrt-db
                  key: user
            - name: app.db.psw
              valueFrom:
                secretKeyRef:
                  name: scrt-db
                  key: password
          ports:
            - containerPort: 8815
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/logs
            name: logs-folder
      volumes:
      - azureFile:
          readOnly: false
          secretName: scrt-applstorage
          shareName: app-logs/report-service
        name: logs-folder