# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: frontend
fullnameOverride: ""
replicaCount: 1

#image
image:
  name:
  tag:
  port: 80
  pullPolicy: IfNotPresent

# reason
reason: unknown

ingress:
  tls: false
  host:
  path: /(.*)
  tlsSecretName:

# tags
tags:
  dev: false
  prod: false

service:
  targetPort: 80
  targetProtocol: TCP

# Resources
resources:
  requests:
    cpu: 10m
    memory: 48Mi
  limits:
    cpu: 50m
    memory: 96Mi

# Security Context
securityContext:
  enabled: true
  fsGroup: 1

# ingress
ingress:
  tls: true

# logs
logs:
  volume:
    secretName:
    shareName:   