apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-applgeneral
data:
  app.auth-server.url: {{ required "auth.url is required" .Values.auth.url }}
  app.db.server: {{ required "db.server is required" .Values.db.server }}
  app.db.name: {{ required "db.name is required" .Values.db.name }}
  rabbitmq.user: {{ required "rabbitmq.user is required" .Values.rabbitmq.user }}
  rabbitmq.psw: {{ required "rabbitmq.psw is required" .Values.rabbitmq.psw }}
  rabbitmq.server: {{ required "rabbitmq.server is required" .Values.rabbitmq.server }}
  rabbitmq.port: " {{ required "rabbitmq.port is required" .Values.rabbitmq.port }}"