apiVersion: v1
kind: Secret
metadata:
  name: scrt-db
data:
  user: {{ required "db.user is required" .Values.db.user | b64enc }}
  password: {{ required "db.psw is required" .Values.db.psw | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: scrt-auth
data:
  user: {{ required "auth.user is required" .Values.auth.user | b64enc }}
  password: {{ required "auth.psw is required" .Values.auth.psw | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: scrt-applstorage
data:
  azurestorageaccountname: {{ required "storage.account is required" .Values.storage.account | b64enc }}
  azurestorageaccountkey: {{ required "storage.secret is required" .Values.storage.secret | b64enc }}