###################################################################################################
# FRONTEND INGRESS
###################################################################################################
{{- $relname := .Release.Name }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-{{ $relname }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.org/client-max-body-size: "50m"
spec:
  {{ if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  {{ end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: {{ include "frontend.versionappname" . | replace "." "" }}
          servicePort: {{ .Values.service.targetPort }}