apiVersion: v1
kind: LimitRange
metadata:
  name: lr-example-prod
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 50m
      memory: 128Mi
    type: Container    
