#---------------------------------------------------------
#  deny ingress/egress
#---------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dev-deny-all
spec:
  podSelector:
    matchLabels:
       app.kubernetes.io/part-of: sample-application
  policyTypes:
  - Ingress
  - Egress