# apiVersion: v1
# kind: ResourceQuota
# metadata:
#  name: rq-nahu-iris-prod
#spec:
#  hard:
#    cpu: 1500m
#    memory: 7Gi
#
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-nahu-iris
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 50m
      memory: 128Mi
    type: Container    
