# Default values for auth-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: auth-service
fullnameOverride: ""
replicaCount: 1

# image
image:
  name:
  tag:
  port: 8812
  pullPolicy: IfNotPresent

# Resources
resources:
  jvmOpts: -Xmx820M -XX:MaxRAM=1024M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

# probes
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8812
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 20
  failureThreshold: 5
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8812
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 5

# telemetry
telemetry:
  level: ERROR

# reason
reason: unknown

# ingress
ingress:
  tls: false
  host:
  path: /api/(oauth/.*)
  tlsSecretName:

# tags
tags:
  dev: false
  prod: false

# Service account identity
serviceAccount: account-iris

# Security context
securityContext:
  enabled: true
  fsGroup: 1
  runAsUser: 10002

# Horizontal Pod Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90

# service
service:
  targetPort: 8812
  targetProtocol: TCP

#logs 
logs:
  volume:
    secretName:
    shareName:
# signing-key for access token
signingKey:
